name: Deploy MkDocs Sites

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build landing page
        run: mkdocs build -f mkdocs.yml -d ../site-output

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build SQL Injection
        run: mkdocs build -f sql-injection/mkdocs.yml -d ../site-output/sql-injection

      - name: Build File Upload Vulnerabilities
        run: mkdocs build -f file-upload-vulnerabilities/mkdocs.yml -d ../site-output/file-upload-vulnerabilities

      - name: Build Race Conditions
        run: mkdocs build -f race-conditions/mkdocs.yml -d ../site-output/race-conditions

      - name: Build Path Traversal
        run: mkdocs build -f path-traversal/mkdocs.yml -d ../site-output/path-traversal

      - name: Build CORS
        run: mkdocs build -f cors/mkdocs.yml -d ../site-output/cors

      - name: Build Web LLM Attacks
        run: mkdocs build -f web-llm-attacks/mkdocs.yml -d ../site-output/web-llm-attacks

      - name: Build API Testing
        run: mkdocs build -f api-testing/mkdocs.yml -d ../site-output/api-testing

      - name: Build Server-side Vulnerabilities
        run: mkdocs build -f server-side-vulnerabilities/mkdocs.yml -d ../site-output/server-side-vulnerabilities

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site-output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

